Lesson 3 button plus accordeon
js-tasks-ru/htmlcss-20230411_mactub07 pull request #5
Opened 2023-04-21 14:05 UTC by Mactub07

2023-04-21 14:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-21 20:27 UTC, GSemikozov requested changes

2023-04-21 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons {
это не часть блока .button, если нужен враппер для более красивого вывода компонента на странице с примером - тогда можно на ней же в теге style

2023-04-21 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
pointer-events: none

2023-04-21 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled {
.button:disabled (общее состояние для всех типов)

2023-04-21 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details > summary {
1-8 - если глобальные сбросы, то в normalize, если на уровне компонента - то через классы

2023-04-21 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 32px;
не совсем по макету

2023-04-21 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.details {
блок .details? на самом деле здесь мы описываем блок .accordion, так что - просто .accordion__details

2023-04-21 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.details__summary {
.accordion__summary

2023-04-21 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.details__content {
.accordion__content

2023-04-24 10:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 10:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-24 10:59 UTC, Mactub07 commented on 03-lection1/01-button/button.css
> +.buttons {
fixed

2023-04-24 11:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-24 11:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-24 11:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-24 11:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-24 11:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-24 20:05 UTC, GSemikozov requested changes

2023-04-24 20:05 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 1rem;
высота при этом точно как в макете? (48)

2023-04-24 20:05 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
лишнее (при pointer-events: none ьудет такой же курсор)

2023-04-24 20:05 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 1px solid var(--button_primary);
проще менять только цвет: border-color

2023-04-24 20:05 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details {
при .accordion__details[open] - padding-bottom: 32px?

2023-04-25 09:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-25 09:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 09:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 09:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 12:24 UTC, GSemikozov requested changes

2023-04-25 12:24 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px;
на 1px выше чем в макете (добавим height: 48px)

2023-04-25 12:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-25 12:53 UTC, GSemikozov approved these changes

2023-04-25 12:54 UTC, merged